baseurl = "https://sasha-kozhukhar.github.io/guatemala_atlas/"
title = "Atlas of languages of Guatemala"
languageCode = "en-us"
publishDir = "docs"
theme = "twentyfourteen"

[blackfriday]
  plainIDAnchors = true